set hidden
set showcmd
set hlsearch
set wildmenu
set smartcase
set ignorecase
filetype indent plugin on
set backspace=indent,eol,start
set autoindent
set nostartofline
set ruler
set scrolloff=5
set laststatus=2
set confirm
set visualbell
set t_vb=
set notimeout ttimeout ttimeoutlen=200
set splitbelow
set splitright
syntax on
set number
set nowrap
filetype on
set hidden

""" Show tab bar even for one tab
set showtabline=2

""" TABBING
set expandtab
set tabstop=2
set shiftwidth=2

let g:auto_save = 1
let g:auto_save_silent = 1

nnoremap <C-E> :e.<CR>
nnoremap <C-N> :bnext<CR>
nnoremap <C-P> :bprev<CR>
nnoremap <C-W> :bw<CR>
nnoremap <C-X> :bdelete<CR>

let g:ctrlp_working_path_mode = 'ra'
let g:ctrlp_map = '<c-o>'
let g:ctrlp_cmd = 'CtrlP'

let g:netrw_banner = 0
let g:netrw_liststyle = 4

